# Generated by Django 5.0.4 on 2024-04-16 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_cmd', models.IntegerField()),
                ('commande_date', models.DateField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.user')),
                ('produit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.produit')),
            ],
        ),
    ]
